language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.1
    - php: 7.2


before_install: if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: composer update --prefer-dist

script: phpunit
